"""
Forensic Report Generator
===========================
Generates structured JSON summaries and official PDF Audio Forensic Dockets.
Designed for zero-persistence environments — all output is in-memory only.
"""

import io
import hashlib
import logging
import time
from typing import Dict, Any, Optional

logger = logging.getLogger("forenlytics.report")

FORENSIC_DISCLAIMER = (
    "This report is generated by an automated acoustic analysis system. "
    "The scores, verdicts, and classifications contained herein are "
    "probabilistic forensic indicators only. They do not constitute "
    "definitive proof of speaker identity or audio authenticity, and "
    "must not be used as standalone evidence in any legal, judicial, "
    "institutional, or regulatory proceeding without independent review "
    "by a qualified forensic audio examiner. Threshold calibration is "
    "based on heuristic defaults; no labeled calibration dataset was used."
)


class ReportGenerator:
    """Generates structured intelligence summaries and official PDF dockets for audio forensics."""

    def generate_json_summary(
        self,
        audio_compare: Optional[Dict[str, Any]] = None,
        audio_deepfake: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        try:
            has_compare = audio_compare is not None and "similarity_score" in audio_compare
            has_deepfake = audio_deepfake is not None and "deepfake_score" in audio_deepfake

            # ── Speaker comparison data ────────────────────────────────────
            sim_score = audio_compare.get("similarity_score", 0) if has_compare else 0
            verdict = audio_compare.get("verdict", "N/A") if has_compare else "N/A"
            conf_level = audio_compare.get("confidence_level", "N/A") if has_compare else "N/A"
            engine_scores = audio_compare.get("engine_scores", {}) if has_compare else {}
            breakdown = audio_compare.get("breakdown", []) if has_compare else []
            file_meta = audio_compare.get("file_metadata", {}) if has_compare else {}
            preprocessing_steps = audio_compare.get("preprocessing_steps", []) if has_compare else []
            threshold_note = audio_compare.get("threshold_note", "") if has_compare else ""

            # ── Deepfake data ──────────────────────────────────────────────
            df_score = audio_deepfake.get("deepfake_score", 0) if has_deepfake else 0
            df_label = audio_deepfake.get("label", "N/A") if has_deepfake else "N/A"
            df_conf = audio_deepfake.get("confidence", "N/A") if has_deepfake else "N/A"
            df_metrics = audio_deepfake.get("metrics", {}) if has_deepfake else {}
            # Use .get() to avoid KeyError if interpretation wasn't populated
            df_interp = audio_deepfake.get(
                "interpretation",
                "Interpretation not available for this analysis."
            ) if has_deepfake else "No deepfake analysis performed."

            # ── Observations ───────────────────────────────────────────────
            obs_parts = []
            if has_compare:
                obs_parts.append(
                    f"Acoustic biometric fusion yielded a speaker similarity score of {sim_score}% "
                    f"(Verdict: {verdict}, Confidence: {conf_level}). "
                    f"Analysis used Microsoft WavLM-Base-Plus-SV as the primary engine."
                )
            if has_deepfake:
                obs_parts.append(
                    f"Synthetic vocoder artifact analysis classified the specimen as '{df_label}' "
                    f"(Anomaly Index: {df_score}%, Diagnostic Confidence: {df_conf})."
                )
            if not has_compare and not has_deepfake:
                obs_parts.append(
                    "No active audio comparison or deepfake analysis data recorded for this session."
                )

            return {
                "case_summary": {
                    "has_speaker_comparison":  has_compare,
                    "has_deepfake_analysis":   has_deepfake,
                    "generated_at":            time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
                    "target_platform":         "Forenlytics Neural Audio Forensics Suite v2.0",
                    "forensic_disclaimer":     FORENSIC_DISCLAIMER,
                },
                "speaker_verification": {
                    "similarity_score":   sim_score,
                    "verdict":            verdict,
                    "confidence_level":   conf_level,
                    "threshold_note":     threshold_note,
                    "engine_scores": {
                        "wavlm":      round(engine_scores.get("wavlm", 0) or 0, 1),
                        "embedding":  round(engine_scores.get("embedding", 0), 1),
                        "biometric":  round(engine_scores.get("biometric", 0), 1),
                        "signal":     round(engine_scores.get("signal", 0), 1),
                    },
                    "breakdown":          breakdown,
                    "file_metadata":      file_meta,
                    "preprocessing_steps": preprocessing_steps,
                },
                "deepfake_diagnostics": {
                    "deepfake_score":  df_score,
                    "label":           df_label,
                    "confidence":      df_conf,
                    "interpretation":  df_interp,
                    "metrics":         df_metrics,
                },
                "final_summary": {
                    "observation": " ".join(obs_parts)
                },
            }
        except Exception as e:
            logger.exception("Audio report summary generation failed")
            return {
                "case_summary": {
                    "has_speaker_comparison": False,
                    "has_deepfake_analysis": False,
                    "generated_at": time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
                },
                "speaker_verification": {"similarity_score": 0, "verdict": "ERROR", "confidence_level": "ERROR"},
                "deepfake_diagnostics": {"deepfake_score": 0, "label": "ERROR", "interpretation": "Report generation error."},
                "final_summary": {"observation": f"Report generation encountered an error: {e}"},
            }

    def generate_pdf(
        self,
        audio_compare: Optional[Dict[str, Any]] = None,
        audio_deepfake: Optional[Dict[str, Any]] = None,
    ) -> io.BytesIO:
        t_start = time.time()
        try:
            try:
                from reportlab.lib.pagesizes import letter
                from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
                from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
                from reportlab.lib import colors
                has_reportlab = True
            except ImportError:
                has_reportlab = False

            data = self.generate_json_summary(audio_compare, audio_deepfake)
            buffer = io.BytesIO()

            if not has_reportlab:
                logger.warning("reportlab not installed — generating plain text fallback.")
                text = (
                    f"FORENLYTICS AUDIO FORENSIC DOCKET\n"
                    f"Generated: {data['case_summary']['generated_at']}\n\n"
                    f"Observation: {data['final_summary']['observation']}\n\n"
                    f"DISCLAIMER: {FORENSIC_DISCLAIMER}\n"
                )
                buffer.write(text.encode("utf-8"))
                buffer.seek(0)
                return buffer

            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=54,
                leftMargin=54,
                topMargin=54,
                bottomMargin=36,
            )
            styles = getSampleStyleSheet()

            # Custom styles
            title_style = ParagraphStyle(
                "DocTitle", parent=styles["Heading1"],
                fontName="Helvetica-Bold", fontSize=18, leading=22,
                alignment=1, spaceAfter=6, textColor=colors.HexColor("#0f172a"),
            )
            subtitle_style = ParagraphStyle(
                "DocSubtitle", parent=styles["Normal"],
                fontName="Helvetica", fontSize=8.5, alignment=1,
                spaceAfter=4, textColor=colors.HexColor("#64748b"),
            )
            section_style = ParagraphStyle(
                "SecHeader", parent=styles["Heading2"],
                fontName="Helvetica-Bold", fontSize=10.5,
                spaceBefore=14, spaceAfter=7, textColor=colors.HexColor("#0284c7"),
            )
            body_style = ParagraphStyle(
                "BodyTextCustom", parent=styles["Normal"],
                fontName="Helvetica", fontSize=8.5, leading=13,
                textColor=colors.HexColor("#334155"),
            )
            caution_style = ParagraphStyle(
                "Caution", parent=styles["Normal"],
                fontName="Helvetica", fontSize=8, leading=12,
                textColor=colors.HexColor("#b45309"),
                borderPadding=(6, 6, 6, 6),
            )

            def make_table(rows, col_widths=(200, 304)):
                t = Table(rows, colWidths=col_widths)
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]))
                return t

            flowables = []

            # ── Header ────────────────────────────────────────────────────
            flowables.append(Paragraph("FORENLYTICS AUDIO FORENSIC INTELLIGENCE DOCKET", title_style))
            flowables.append(Paragraph(
                f"Official Neural Biometric & Synthetics Analysis Record  •  "
                f"Generated {data['case_summary']['generated_at']}",
                subtitle_style,
            ))
            flowables.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=8))

            # ── A. Examination Metadata ─────────────────────────────────────
            flowables.append(Paragraph("A. FORENSIC EXAMINATION METADATA", section_style))
            flowables.append(make_table([
                ["Platform Suite", "Forenlytics Audio Forensic Engine v2.0"],
                ["Primary Speaker Verification Model", "Microsoft WavLM-Base-Plus-SV (x-vector, VoxCeleb fine-tuned)"],
                ["Secondary Embedding Engine", "SpeechBrain ECAPA-TDNN (spkrec-ecapa-voxceleb) / Wav2Vec2 fallback"],
                ["Synthetic Anomaly Detection", "Signal-level heuristics (ZCR variance, Spectral Rolloff, Onset, Embedding variance)"],
                ["Analysis Scope", "In-memory only — no audio data persisted to disk"],
            ]))

            # ── B. File Chain of Custody ────────────────────────────────────
            sv = data["speaker_verification"]
            fm = sv.get("file_metadata", {})
            has_file_meta = bool(fm)

            if has_file_meta:
                flowables.append(Paragraph("B. FILE CHAIN OF CUSTODY", section_style))
                f1 = fm.get("audio_1", {})
                f2 = fm.get("audio_2", {})
                custody_rows = [
                    ["", "Target Sample (Audio 1)", "Comparison Sample (Audio 2)"],
                    ["SHA-256 Hash",
                     f1.get("sha256", "N/A")[:32] + "...",
                     f2.get("sha256", "N/A")[:32] + "..."],
                    ["Raw Duration",
                     f"{f1.get('raw_duration_sec', 'N/A')}s",
                     f"{f2.get('raw_duration_sec', 'N/A')}s"],
                    ["Speech Duration (post-VAD)",
                     f"{f1.get('speech_duration_sec', 'N/A')}s",
                     f"{f2.get('speech_duration_sec', 'N/A')}s"],
                    ["Analysis Sample Rate",
                     f"{f1.get('sample_rate', 16000)} Hz",
                     f"{f2.get('sample_rate', 16000)} Hz"],
                ]
                t3col = Table(custody_rows, colWidths=[130, 187, 187])
                t3col.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ]))
                flowables.append(t3col)

            # ── C. Speaker Verification ─────────────────────────────────────
            flowables.append(Paragraph("C. SPEAKER VERIFICATION & NEURAL BIOMETRIC MATCH", section_style))
            eng = sv.get("engine_scores", {})
            wavlm_val = f"{eng.get('wavlm', 0):.1f}%" if eng.get('wavlm') is not None else "OFFLINE"
            sv_rows = [
                ["Composite Similarity Score", f"{sv.get('similarity_score', 0)}%"],
                ["Forensic Verdict", sv.get("verdict", "N/A")],
                ["Confidence Level", sv.get("confidence_level", "N/A")],
                ["WavLM-Base-Plus-SV Score", wavlm_val],
                ["Secondary Embedding Score", f"{eng.get('embedding', 0):.1f}%"],
                ["Vocal Biometrics Score", f"{eng.get('biometric', 0):.1f}%"],
                ["Signal Environment Score", f"{eng.get('signal', 0):.1f}%"],
            ]
            flowables.append(make_table(sv_rows))
            if sv.get("threshold_note"):
                flowables.append(Spacer(1, 4))
                flowables.append(Paragraph(f"Threshold Note: {sv['threshold_note']}", body_style))

            # Breakdown
            if sv.get("breakdown"):
                flowables.append(Spacer(1, 6))
                flowables.append(Paragraph("Engine Analysis Breakdown:", body_style))
                for item in sv["breakdown"]:
                    flowables.append(Paragraph(f"• {item}", body_style))

            # Preprocessing steps
            if sv.get("preprocessing_steps"):
                flowables.append(Spacer(1, 6))
                flowables.append(Paragraph("Preprocessing Steps Applied:", body_style))
                for step in sv["preprocessing_steps"]:
                    flowables.append(Paragraph(f"  – {step}", body_style))

            # ── D. Deepfake Diagnostics ─────────────────────────────────────
            df = data["deepfake_diagnostics"]
            flowables.append(Paragraph("D. DEEPFAKE & SYNTHETIC ANOMALY EVALUATION", section_style))
            df_metrics_dict = df.get("metrics", {})
            df_rows = [
                ["Anomaly Classification Verdict", df.get("label", "N/A")],
                ["Synthetic Anomaly Probability", f"{df.get('deepfake_score', 0)}%"],
                ["Diagnostic Confidence", df.get("confidence", "N/A")],
                ["ZCR Variance", str(df_metrics_dict.get("zcr_variance", "N/A"))],
                ["Spectral Rolloff Variance", str(df_metrics_dict.get("rolloff_variance", "N/A"))],
                ["Embedding Temporal Variance", str(df_metrics_dict.get("embedding_variance", "N/A"))],
            ]
            flowables.append(make_table(df_rows))
            if df.get("interpretation"):
                flowables.append(Spacer(1, 4))
                flowables.append(Paragraph(f"Interpretation: {df['interpretation']}", body_style))

            # ── E. Expert Forensic Summary ──────────────────────────────────
            flowables.append(Paragraph("E. FORENSIC SYNTHESIS & OPINION", section_style))
            flowables.append(Paragraph(data["final_summary"]["observation"], body_style))

            # ── F. Legal Disclaimer ─────────────────────────────────────────
            flowables.append(Spacer(1, 10))
            flowables.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=6))
            flowables.append(Paragraph("FORENSIC DISCLAIMER", section_style))
            flowables.append(Paragraph(FORENSIC_DISCLAIMER, caution_style))

            doc.build(flowables)
            buffer.seek(0)
            elapsed = round(time.time() - t_start, 3)
            logger.info(f"PDF docket generated in {elapsed}s")
            return buffer

        except Exception as e:
            logger.exception("PDF generation failed")
            buffer = io.BytesIO()
            buffer.write(f"PDF generation failed: {e}".encode("utf-8"))
            buffer.seek(0)
            return buffer


report_generator = ReportGenerator()
